apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: e5vtrpqkx-nodejs 
  janus-idp.io/tekton: e5vtrpqkx-nodejs
  backstage.io/kubernetes-id: e5vtrpqkx-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e5vtrpqkx-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml